all: bruteforce divideandconquer enhanceddnc

bruteforce:
	g++ bruteforce.cpp -o bruteforce
	mcs bruteforce.cs

divideandconquer:
	g++ divideandconquer.cpp -o divideandconquer

enhanceddnc:
	g++ enhanceddnc.cpp -o enhanceddnc

clean:
	rm -f bruteforce divideandconquer enhanceddnc *.exe
